steps:
  build:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      # Lint
      - "nix develop --command bash -c 'dotnet tool restore && ./hooks/pre-push'"
      # Test
      - nix develop --command dotnet -- test
      - nix develop --command dotnet -- test --configuration Release
      # Perform build
      - "pushd RaftFable && nix develop --command npm -- install && popd"
      - "pushd RaftFable && nix develop --command npm -- run-script build && popd"

    when:
      - event: "push"
        evaluate: 'CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH'
      - event: "pull_request"
