name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore Raft.sln
    - name: Build
      run: dotnet build Raft.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Raft.sln --no-restore --verbosity normal
    - name: Install Fantomas
      run: dotnet tool restore
    - name: Run Fantomas
      run: dotnet tool run fantomas --check .
